---------------------------------------------------------
-- Stripe charges
-- Note - subscriptions in this table lack product name,
-- which is added in later query
---------------------------------------------------------

config { type: "view" }

select
  date(datetime(created, "America/New_York"))  as charge_date,
  customer as stripe_customer_id,
  id as charge_id,
  captured as charge_status,
  invoice as invoice_id,
  description, -- "Order #" comes from Membermouse
  metadata,
  json_extract_scalar(json_query(metadata, '$.ProductDescription')) as product_name,
  json_extract_scalar(json_query(metadata, '$.clientOrderId')) as client_order_id
from `tsg-transaction-data.stripe_export.stripe_charges_8589937017`
