------------------------
-- Stripe subscriptions
------------------------

config { type: "view" }

select
    date(datetime(TIMESTAMP_SECONDS(created), "America/New_York")) as invoice_date,
    datetime(TIMESTAMP_SECONDS(created), "America/New_York") as invoice_dt,
    id as invoice_id,
    json_extract_scalar(lines, '$.data[0].plan.name') as product_name,
    charge as charge_id
from `eng-particle-420006.airbyte.STRIPE_invoices` 

union all

select

    date(datetime(TIMESTAMP_SECONDS(created), "America/New_York")) as invoice_date,
    datetime(TIMESTAMP_SECONDS(created), "America/New_York") as invoice_dt,
    id as invoice_id,
    json_extract_scalar(lines, '$.data[0].plan.name') as product_name,
    cast(null as string) as charge_id
from `eng-particle-420006.airbyte.STRIPE_SCG_invoices`
