-------------------------------------
-- Samcart customer ID and charge ID
-------------------------------------

config { type: "view" }

select
    date(datetime(created_at, "America/New_York")) as charge_date,
    customer_id as sam_customer_id,
    order_id as transaction_id,
    processor_transaction_id as charge_id,
    case
        when charge_refund_status = 'refunded' then 'refund'
        else 'charge'
    end as charge_type,
    case
        when charge_refund_status = 'refunded' then - total / 100
        else total / 100
    end as charge_amount,
    lower(processor_name) as processor_name
from `tsg-transaction-data.samcart_export.samcart_charges_8589937073`
where test_mode = false
