--------------------------------------------------
-- Paypal transactions coming from checkout champ
--------------------------------------------------

config { type: "view" }

select
    date(dateCreated) as transaction_date,
    datetime(dateCreated, "America/New_York") as transaction_dt,
    clientOrderId as transaction_id,
    case
        when txnType = 'SALE' then 'charge'
        when txnType = 'REFUND' then 'refund'
        when txnType = 'VOID' then 'void'
    end as transaction_type,
    case
        when txnType = 'REFUND' then -cast(totalAmount as numeric)
        else cast(totalAmount as numeric)
    end as transaction_amount,
    -- transaction_fee,
      json_extract_scalar(item, '$.product') as product_name,
      json_extract_scalar(item, '$.price') as product_price,
    emailAddress as customer_email,
    merchantTxnId as charge_id,
    case
        when lower(merchant) like '%paypal%' then 'paypal'
        when lower(merchant) like '%stripe%' then 'stripe'
        when lower(merchant) like '%checkout%prod%' then 'checkout.com'
    end as merchant
from `tsg-transaction-data.checkout_champ_export.checkout_champ_transactions_8589937074`, unnest(json_extract_array(items)) as item
where
    lower(merchant) not like '%test%'
    -- and clientOrderId = 'F00EE0742D' -- debugging