config { type: "view" }

select
    transaction_date,
    transaction_id,
    transaction_type,
    transaction_amount,
    Transaction_fee,
    product_name,
    product_category,
    lower(ifnull(customer_email,"")) as customer_email,
    utm_source,
    dense_rank() over (partition by lower(customer_email) order by transaction_date asc) as groupid
from ${ref('mart_transaction_utm_source')} 
where (ifnull(transaction_type,"")="charge")