----------------------------------------------------
-- Stripe balance transaction data and product name
----------------------------------------------------

config { type: "view" }


select
     date(TIMESTAMP_SECONDS(created), "America/New_York") transaction_date,
    datetime(TIMESTAMP_SECONDS(created), "America/New_York") as transaction_dt,
--   date(datetime(created, "America/New_York"))  as transaction_date,
--   datetime(created, "America/New_York") as transaction_dt,
  id as transaction_id,
  reporting_category as transaction_type,
  (amount/100) as amount,
  (fee/100) as fee,
  source as charge_id,
  description as product_name
from  `eng-particle-420006.airbyte.STRIPE_balance_transactions`


union all

select
     date(TIMESTAMP_SECONDS(created), "America/New_York") transaction_date,
    datetime(TIMESTAMP_SECONDS(created), "America/New_York") as transaction_dt,
--   date(datetime(created, "America/New_York"))  as transaction_date,
--   datetime(created, "America/New_York") as transaction_dt,
  id as transaction_id,
  reporting_category as transaction_type,
  (amount/100) as amount,
  (fee/100) as fee,
  source as charge_id,
  description as product_name
from  `eng-particle-420006.airbyte.STRIPE_SCG_balance_transactions`