config { type: "view" }

-- Stripe balance transaction data and product name
select
  date(datetime(created, "America/New_York"))  as transaction_date,
  id as transaction_id,
  reporting_category as transaction_type,
  (amount/100) as amount,
  (fee/100) as fee,
  source as charge_id,
  description as product_name
from
  `tsg-transaction-data.stripe_export.stripe_balance_transactions_8589937017`