----------------------------------------
-- checkout champ order id and UTM data
-- Use the Checkout champ orders table
-- because it has the best data, including UTMs.
----------------------------------------

config { type: "view" }

select
    date(dateCreated) as order_date,
    cast(totalAmount as float64) as order_amount,
    clientOrderId as transaction_id,
    UTMSource as utm_source,
    UTMMedium as utm_medium,
    UTMCampaign as utm_campaign,
    UTMContent as utm_content,
    UTMTerm as utm_term
from `tsg-transaction-data.checkout_champ_export.checkout_champ_orders_8589937074`
where orderStatus not in ('PARTIAL', 'REFUNDED')
