config { type: "table" }

-- Get UTM source of Checkout Champ Stripe transactions 
with 

stg_stripe_charges as   (
    select 
            client_order_id,
            charge_id 
    from ${ref('stg_stripe_charge')}  
    where client_order_id is not null
)
select 
    charge_id,
    utm_source
from stg_stripe_charges
left join ${ref('stg_checkout_champ')}    
using (client_order_id)

