------------------------------------
-- Query creates all-revenue table
------------------------------------

config { type: "incremental",
  bigquery: {
    partitionBy:  "transaction_date"
  }
}

${when(incremental(), `delete ${self()} where transaction_date >  (select max(transaction_date) from ${self()});` )}


-- Transactions
select
  transaction_date,
  transaction_id,
  transaction_type,
  transaction_amount,
  transaction_fee,
  product_name,
  product_category,
  customer_email,
  utm_source
from ${ref('int_master_transaction')}

${when(incremental(), `where transaction_date > (select max(transaction_date) from ${self()})`) }