------------------------------------
-- Query creates all-revenue table
------------------------------------

config { type: "table" ,
    bigquery: {
        partitionBy:  "transaction_date"
    }
}


-- Transactions
select
  transaction_date,
  transaction_id,
  transaction_type,
  transaction_amount,
  transaction_fee,
  product_name,
  product_category,
  customer_email,
  utm_source
from ${ref('int_master_transaction')}

