config { type: "table" }

select 
  t1.transaction_date,
  t1.transaction_id ,
  t1.transaction_type ,
  t1.amount as transaction_amount,
  t1.fee as transaction_fee,
  product_name,
  t1.product_category,
  t1.charge_id as balance_trans_table_charge_id,
  t2.charge_id as charge_id,
  t2.email as customer_email
FROM ${ref('mart_joinq4andq2')}   t1
left join  ${ref('mart_customer_email')}   t2
on t1.charge_id=t2.charge_id


 