config { type: "table" ,
    bigquery: {
        partitionBy:  "transaction_date"
    }
}

with

main as (
select
    transaction_date,
    transaction_id,
    transaction_type,
    transaction_amount,
    Transaction_fee,
    product_name,
    product_category,
    lower(ifnull(customer_email,"")) as customer_email,
    utm_source,
    dense_rank() over (partition by lower(customer_email) order by transaction_date asc) as groupid
from ${ref('int_stripe_balance_transaction')}
where ifnull(transaction_type, "") = "charge"
),


group_start_dates as (
  select 
    customer_email, 
    groupid,
    min(transaction_date) as group_start_date 
  from main 
  group by 1,2
),

prev_start_date as (
  select
      group_start_date,
      customer_email,
      groupid as groupid,
      lag(group_start_date) over (partition by customer_email order by group_start_date asc) as previous_group_start_date
  from group_start_dates
)


select
  t2.transaction_date,
  t2.transaction_id,
  t2.transaction_type,
  t2.transaction_amount,
  t2.transaction_fee,
  t2.product_name,
  t2.product_category,
  t2.customer_email,
  t2.utm_source,
  coalesce(date_diff(t2.transaction_date, t1.previous_group_start_date, day), 0) as days
from prev_start_date      t1
right join main           t2
on
  t1.customer_email=t2.customer_email
  and t1.group_start_date=t2.transaction_date