----------------------------------------
-- Query creates buyer-breakdown table
----------------------------------------

config { type: "incremental" ,
    bigquery: {
        partitionBy:  "transaction_date"
    }
}
${when(incremental(), `delete ${self()} where transaction_date >  (select max(transaction_date) from ${self()});` )}


with

-- groupid indicates transaction order for customer (1, 2... n)
transactions as (
  select
    transaction_date,
    transaction_id,
    transaction_type,
    transaction_amount,
    Transaction_fee,
    product_name,
    product_category,
    lower(ifnull(customer_email,"")) as customer_email,
    utm_source,
    dense_rank() over (partition by lower(customer_email) order by transaction_date asc) as groupid
  from ${ref('int_stripe_balance_transaction')}
  where ifnull(transaction_type, "") = "charge"
),

-- Find date of nth transaction of a customer
group_start_dates as (
  select 
    customer_email, 
    groupid,
    min(transaction_date) as group_start_date 
  from transactions 
  group by 1, 2
),

-- Find date of previous transaction for a customer
prev_start_date as (
  select
    group_start_date,
    customer_email,
    groupid,
    lag(group_start_date) over (partition by customer_email order by group_start_date asc) as previous_group_start_date
  from group_start_dates
),

-- Number of days since current to previous transaction
-- Used to categorize buyers as active, new or reactivated
buyer_breakdown as (
  select
    transaction_date,
    transaction_id,
    transaction_type,
    transaction_amount,
    transaction_fee,
    product_name,
    product_category,
    t1.customer_email,
    utm_source,
    coalesce(date_diff(t2.transaction_date, t1.previous_group_start_date, day), 0) as days
  from prev_start_date         t1
  right join transactions      t2
  on
    t1.customer_email = t2.customer_email
    and t1.group_start_date = t2.transaction_date
)

select *
from buyer_breakdown

${when(incremental(), `where transaction_date > (select max(transaction_date) from ${self()})`) }