------------------------------------------
-- Query creates velocity-of-return table
------------------------------------------

-- Cohort updates columns (not incremental)
config { type: "table" ,
    bigquery: {
        partitionBy:  "transaction_date"
    }
}


with

-- Add first transaction date and days_in_system
transactions as  (
  select
    transaction_date,
    transaction_id,
    transaction_type,
    transaction_amount,
    Transaction_fee,
    product_name,
    product_category,
    lower(ifnull(customer_email, "")) as customer_email,
    utm_source,
    min(transaction_date) over (partition by lower(ifnull(customer_email,"")) ) as customer_min_transDate,
    if(((min(transaction_date) over (partition by lower(ifnull(customer_email,"")) ) is null)
      or (transaction_date is null)), 0, date_diff(transaction_date, min(transaction_date) over (partition by lower(ifnull(customer_email,""))), day)) as days_in_system
  from ${ref('int_master_transaction')}
  where regexp_contains(ifnull(transaction_type,""),r"(?i)charge")
),

-- Add rank & days categories 
vor_rank_days as (
  select
    customer_email,
    product_name,
    days_in_system,
    product_category,
    utm_source,
    transaction_date,
    transaction_amount,
    customer_min_transDate,
    case
      when customer_min_transDate is null                  then ''
      when (days_in_system  = 0                          ) then '1'
      when (days_in_system >= 0 and days_in_system <=   7) then '2'
      when (days_in_system >= 0 and days_in_system <=  14) then '3'
      when (days_in_system >= 0 and days_in_system <=  30) then '4'
      when (days_in_system >= 0 and days_in_system <=  60) then '5'
      when (days_in_system >= 0 and days_in_system <=  90) then '6'
      when (days_in_system >= 0 and days_in_system <= 120) then '7'
      when (days_in_system >= 0 and days_in_system <= 365) then '8'
      when (                        days_in_system >  365) then '9'         
    end as rank,
    case
      when customer_min_transDate is null                  then ""
      when (days_in_system  = 0                          ) then "day 0"
      when (days_in_system >= 0 and days_in_system <=   7) then "day 7"
      when (days_in_system >= 0 and days_in_system <=  14) then "day 14"
      when (days_in_system >= 0 and days_in_system <=  30) then "day 30"
      when (days_in_system >= 0 and days_in_system <=  60) then "day 60"
      when (days_in_system >= 0 and days_in_system <=  90) then "day 90"
      when (days_in_system >= 0 and days_in_system <= 120) then "day 120"
      when (days_in_system >= 0 and days_in_system <= 365) then "day 365"
      when (                        days_in_system >  365) then "day 365+"  
    end as days
  from transactions
),

-- Cohort revenues for each customer
vor_daysums  as  (
  select
    customer_email,
    customer_min_transDate,
    sum(if((days_in_system                          =   0), transaction_amount, 0)) as day0_sum,
    sum(if((days_in_system >= 0 and days_in_system <=   7), transaction_amount, 0)) as day7_sum,
    sum(if((days_in_system >= 0 and days_in_system <=  14), transaction_amount, 0)) as day14_sum,
    sum(if((days_in_system >= 0 and days_in_system <=  39), transaction_amount, 0)) as day30_sum,
    sum(if((days_in_system >= 0 and days_in_system <=  69), transaction_amount, 0)) as day60_sum,
    sum(if((days_in_system >= 0 and days_in_system <=  99), transaction_amount, 0)) as day90_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 129), transaction_amount, 0)) as day120_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 365), transaction_amount, 0)) as day365_sum,
    sum(if((days_in_system >= 0                          ), transaction_amount, 0)) as day365Beyond_sum  -- sum ALL for customer
  from  transactions
  group by
    customer_email,
    customer_min_transDate
),

-- Velocity of return table
-- For multiple transactions, revenue is summed then
-- averaged by count of transactions (Looker function)
vor as (
  select
    t1.customer_email,
    transaction_date,
    extract(year from transaction_date) as year,
    extract(month from transaction_date) as month,
    product_name, 
    transaction_amount,
    utm_source,
    product_category,
    t1.customer_min_transDate,
    rank,
    days_in_system,
    days,     -- e.g. "day 14"
    day0_sum,
    day7_sum ,
    day14_sum,
    day30_sum,
    day60_sum,
    day90_sum,
    day120_sum,
    day365_sum,
    day365Beyond_sum
  from      vor_rank_days        t1
  left join vor_daysums          t2
  on t1.customer_email = t2.customer_email
  order by 1, 2
)

select *
from vor
--where customer_email = 'zzhang29@gmail.com' -- COMMENT THIS OUT WHEN NOT TESTING!