config { type: "table" ,
    bigquery: {
      partitionBy:  "transaction_date"
    }
}

-- Query does velocity of return calculations

with

-- get transaction data and utm source of customer
prime as  (
  select
    transaction_date,
    transaction_id,
    transaction_type,
    transaction_amount,
    Transaction_fee,
    product_name,
    product_category,
    lower(ifnull(customer_email,"")) as customer_email,
    utm_source,
    min(transaction_date) over (partition by lower(ifnull(customer_email,"")) ) as customer_min_transDate,
    if(((min(transaction_date) over (partition by lower(ifnull(customer_email,"")) ) is null)
      or (transaction_date is null)),0,date_diff(transaction_date,min(transaction_date) over (partition by lower(ifnull(customer_email,""))), day)) as days_in_system
  from ${ref('int_stripe_balance_transaction')}
  where regexp_contains(ifnull(transaction_type,""),r"(?i)charge")
),

-- calculate first transaction date of customer
cust_min_transaction_date as  (
  select customer_email,
    min(transaction_date) as customer_min_transDate 
  from prime
  group by 1
),

-- Add first transaction date column
first_transaction as (
select 
  transaction_date,
  transaction_id,
  transaction_type,
  transaction_amount,
  Transaction_fee,
  product_name,
  product_category,
  a.customer_email as customer_email,
  utm_source,
  b.customer_min_transDate,
  if((b.customer_min_transDate is null or a.transaction_date is null),0,date_diff(transaction_date,b.customer_min_transDate,day))
  as days_in_system
from prime                             a
left join cust_min_transaction_date    b
on a.customer_email = b.customer_email
),


-- Days in system
day0_365sum  as  (
  select
    customer_Email as customer_Email,
    sum(if((days_in_system =  0),transaction_amount, 0)) as day0_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 7), transaction_amount, 0)) as day7_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 14), transaction_amount, 0)) as day14_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 39),transaction_amount, 0)) as day30_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 69),transaction_amount, 0)) as day60_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 99),transaction_amount, 0)) as day90_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 129),transaction_amount, 0)) as day120_sum,
    sum(if((days_in_system >= 0 and days_in_system <= 365),transaction_amount, 0)) as day365_sum,
    sum(if((days_in_system >= 0 ),transaction_amount, 0)) as day365Beyond_sum,
    customer_min_transDate as customer_min_transDate
  from  first_transaction
  group by
    customer_Email,
    customer_min_transDate
),

-- Add
vor_col as (
  select
    customer_Email as customer_Email,
    product_name as product_name,
    days_in_system as days_in_system,
    case
      when customer_min_transDate is null then ""
      when days_in_system <= 0 then '1'
      when (days_in_system >= 0 and days_in_system <= 7) then '2'
      when (days_in_system >= 0 and days_in_system<=14) then '3'
      when (days_in_system >= 0 and days_in_system<=30) then '4'
      when (days_in_system >= 0 and days_in_system <= 60) then '5'
      when (days_in_system >= 0 and days_in_system<=90) then '6'
      when (days_in_system >= 0 and days_in_system<=120) then '7'
      when (days_in_system >= 0 and days_in_system<=365) then '8'
      when (days_in_system >= 0 and days_in_system>=365) then '9'
    end as rank,
    case
      when customer_min_transDate is null then ""
      when days_in_system<=0 then "day 0"
      when (days_in_system>=0 and days_in_system<=7) then "day 7"
      when (days_in_system>=0 and days_in_system<=14) then "day 14"
      when (days_in_system>=0 and days_in_system<=30) then "day 30"
      when (days_in_system>=0 and days_in_system<=60) then "day 60"
      when (days_in_system>=0 and days_in_system<=90) then "day 90"
      when (days_in_system>=0 and days_in_system<=120) then "day 120"
      when (days_in_system>=0 and days_in_system<=365) then "day 365"
      when (days_in_system>=0 and days_in_system>=365) then "day 365+"
    end as days,
    product_category as product_category,
    utm_source as utm_source,
    transaction_date as transaction_date,
    transaction_amount as transaction_amount,
    customer_min_transDate as customer_min_transDate
  from first_transaction
)


select
  ifnull(t1.customer_email,'') as customer_email ,
  t1.product_name , 
  t1.days_in_system  ,
  t1.rank ,
  t1.days,
  t2.day0_sum ,
  t2.day7_sum ,
  t2.day14_sum,
  t2.day30_sum,
  t2.day60_sum,
  t2.day90_sum,
  t2.day120_sum ,
  t2.day365_sum,
  t2.day365Beyond_sum ,
  t1.product_category ,
  extract(year from transaction_date) as year,
extract(month from transaction_date) as month,
  t1.utm_source as utm_source,
  t1.transaction_date as transaction_date,
  t1.transaction_amount as transaction_amount,
  t1.customer_min_transDate as customer_min_transDate
from VOR_col            t1
left join day0_365sum   t2
on
  t1.customer_email=t2.customer_email
  order by 1,2,3,4,5,6,7,8,9,10,11,12,13,14
