config { type: "view" }

select
    charge_id,
    email
  from ${ref('stg_samcart_charge')} 
  left join ${ref('stg_samcart_customer')}  
  using (sam_customer_id)
  where where processor_transaction_id like 'py_%' like 'py_%'


union all  

select 
    charge_id,
    email
  from ${ref('stg_stripe_charge')}  
  left join  ${ref('stg_stripe_customer')}   
  using (stripe_customer_id)
  where
    charge_id LIKE "ch_%"
    and charge_status = true